export function Terms() {
  return (
    <div className="min-h-screen py-24 px-6">
      <div className="mx-auto max-w-3xl">
        <a
          href="/"
          className="inline-flex items-center gap-2 text-sm text-[var(--color-ink-muted)] hover:text-[var(--color-ink)] transition-colors mb-10"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
            <path d="M10 4l-4 4 4 4" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
          Back to home
        </a>

        <h1 className="font-serif text-4xl md:text-5xl font-bold text-[var(--color-ink)] tracking-tight mb-4">
          Terms of Service
        </h1>
        <p className="text-sm text-[var(--color-ink-faint)] mb-12">
          Effective Date: March 31, 2026
        </p>

        <div className="space-y-10 text-[var(--color-ink-muted)] leading-relaxed">
          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">1. Acceptance of Terms</h2>
            <p>
              By installing or using the bubb Chrome Extension ("Service"), you agree to these Terms of Service. If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">2. Description of Service</h2>
            <p>
              bubb is a browser extension that provides AI-powered explanations for text highlighted on webpages. The Service includes text highlighting, AI-generated explanations at multiple depth levels, note saving, topic organization, and follow-up conversations.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">3. User Accounts</h2>
            <p>
              You must sign in with a Google account to use bubb. You are responsible for maintaining the security of your account and all activity that occurs under it.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to reverse-engineer, decompile, or disassemble the extension</li>
              <li>Abuse, overload, or interfere with the Service's infrastructure</li>
              <li>Share or redistribute your account access</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">5. Intellectual Property</h2>
            <p>
              The Service, including its code, design, and branding, is owned by bubb. AI-generated explanations are provided for your personal use. You retain ownership of any notes or content you create.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">6. AI-Generated Content</h2>
            <p>
              Explanations are generated by third-party AI models (OpenAI, Anthropic) and may contain inaccuracies. bubb does not guarantee the accuracy, completeness, or reliability of AI-generated content. Use your own judgment.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">7. Pricing & Subscriptions</h2>
            <p>
              bubb offers a free tier with daily usage limits and a paid tier with expanded access. Pricing and feature availability may change. Paid subscriptions can be cancelled at any time.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">8. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for violation of these terms. You may stop using the Service at any time by uninstalling the extension.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">9. Limitation of Liability</h2>
            <p>
              The Service is provided "as is" without warranties of any kind. bubb shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms as the product evolves. Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-serif text-xl font-semibold text-[var(--color-ink)] mb-3">11. Contact</h2>
            <p>
              Questions about these terms? Contact us at{' '}
              <a href="mailto:dcabansay123@gmail.com" className="text-[var(--color-coral)] hover:underline">
                dcabansay123@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
